version: '3'

volumes:
  pgdata:

services:
  test_postgres:
    restart: always
    image: kiasaki/alpine-postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  test_django:
    build: .
    image: django-rest-test
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    links:
      - test_postgres
    depends_on:
      - test_postgres
    env_file:
      - .env